config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :postcode_searches, only: %i[new create]

  namespace :admin do
    resources :allowed_areas
    resources :allowed_postcodes
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'postcode_searches#new'
end

app/models/admin.rb
# frozen_string_literal: true

module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/allowed_area.rb
# frozen_string_literal: true

module Admin
  class AllowedArea < ApplicationRecord
    validates :area, presence: true
    validates :area, uniqueness: true

    before_save { normalised_area }

    private

    def normalised_area
      return if area.nil?

      self.area = area.split(' ').first.downcase
    end
  end
end

app/models/admin/allowed_postcode.rb
# frozen_string_literal: true

module Admin
  class AllowedPostcode < ApplicationRecord
    POSTCODE_REGEX = /\A[a-zA-Z]{1,2}[0-9][a-zA-Z0-9]? ?[0-9][a-zA-Z]{2}\z/.freeze

    validates :postcode, presence: true
    validates :postcode, uniqueness: true
    validates_format_of :postcode, with: POSTCODE_REGEX

    before_save { normalise_postcode }

    private

    def normalise_postcode
      self.postcode = postcode.delete(' ').downcase
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/admin/allowed_areas_controller.rb
# frozen_string_literal: true

module Admin
  class AllowedAreasController < BaseController
    before_action :set_admin_allowed_area, only: %i[show edit update destroy]

    # GET /admin/allowed_areas
    def index
      @admin_allowed_areas = Admin::AllowedArea.all
    end

    # GET /admin/allowed_areas/1
    def show; end

    # GET /admin/allowed_areas/new
    def new
      @admin_allowed_area = Admin::AllowedArea.new
    end

    # GET /admin/allowed_areas/1/edit
    def edit; end

    # POST /admin/allowed_areas
    def create
      @admin_allowed_area = Admin::AllowedArea.new(admin_allowed_area_params)

      if @admin_allowed_area.save
        redirect_to @admin_allowed_area, notice: 'Allowed area was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /admin/allowed_areas/1
    def update
      if @admin_allowed_area.update(admin_allowed_area_params)
        redirect_to @admin_allowed_area, notice: 'Allowed area was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /admin/allowed_areas/1
    def destroy
      @admin_allowed_area.destroy
      redirect_to admin_allowed_areas_url, notice: 'Allowed area was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_allowed_area
      @admin_allowed_area = Admin::AllowedArea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_allowed_area_params
      params.require(:admin_allowed_area).permit(:area)
    end
  end
end

app/controllers/admin/allowed_postcodes_controller.rb
# frozen_string_literal: true

module Admin
  class AllowedPostcodesController < BaseController
    before_action :set_admin_allowed_postcode, only: %i[show edit update destroy]

    # GET /admin/allowed_postcodes
    def index
      @admin_allowed_postcodes = Admin::AllowedPostcode.all
    end

    # GET /admin/allowed_postcodes/1
    def show; end

    # GET /admin/allowed_postcodes/new
    def new
      @admin_allowed_postcode = Admin::AllowedPostcode.new
    end

    # GET /admin/allowed_postcodes/1/edit
    def edit; end

    # POST /admin/allowed_postcodes
    def create
      @admin_allowed_postcode = Admin::AllowedPostcode.new(admin_allowed_postcode_params)

      if @admin_allowed_postcode.save
        redirect_to @admin_allowed_postcode, notice: 'Postcode was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /admin/allowed_postcodes/1
    def update
      if @admin_allowed_postcode.update(admin_allowed_postcode_params)
        redirect_to @admin_allowed_postcode, notice: 'Postcode was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /admin/allowed_postcodes/1
    def destroy
      @admin_allowed_postcode.destroy
      redirect_to admin_allowed_postcodes_url, notice: 'Postcode was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_allowed_postcode
      @admin_allowed_postcode = Admin::AllowedPostcode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_allowed_postcode_params
      params.require(:admin_allowed_postcode).permit(:postcode)
    end
  end
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

module Admin
  class BaseController < ApplicationController
    http_basic_authenticate_with(
      name: ENV['BASIC_AUTH_NAME'],
      password: ENV['BASIC_AUTH_PASSWORD']
    )
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private

  def postcodes_cache
    @postcodes_cache ||= PostcodesCache.new
  end

  def postcodes_io
    PostcodesIo.new(cache: postcodes_cache)
  end
end

app/controllers/postcode_searches_controller.rb
# frozen_string_literal: true

class PostcodeSearchesController < ApplicationController
  def new; end

  def create
    message = ResponseLogic.new(
      normalised_postcode,
      postcodes_io.find(normalised_postcode)
    ).call

    redirect_to(root_url, flash: message)
  end

  private

  def normalised_postcode
    permitted_params[:postcode].delete(' ').downcase
  end

  def permitted_params
    params.permit(:postcode, :authenticity_token, :commit)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/allowed_areas/_allowed_area.html.erb
<div id="<%= dom_id allowed_area %>">
  <p>
    <strong>Area:</strong>
    <%= allowed_area.area %>
  </p>

</div>

app/views/admin/allowed_areas/_form.html.erb
<%= form_with(model: admin_allowed_area) do |form| %>
  <% if admin_allowed_area.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_allowed_area.errors.count, "error") %> prohibited this admin_allowed_area from being saved:</h2>

      <ul>
        <% admin_allowed_area.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :area, style: "display: block" %>
    <%= form.text_field :area %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/allowed_areas/edit.html.erb
<h1>Editing allowed area</h1>

<%= render "form", admin_allowed_area: @admin_allowed_area %>

<br>

<div>
  <%= link_to "Show this allowed area", @admin_allowed_area %> |
  <%= link_to "Back to allowed areas", admin_allowed_areas_path %>
</div>

app/views/admin/allowed_areas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Allowed areas</h1>

<div id="admin_allowed_areas">
  <% @admin_allowed_areas.each do |admin_allowed_area| %>
    <%= render admin_allowed_area %>
    <p>
      <%= link_to "Show this allowed area", admin_allowed_area %>
    </p>
  <% end %>
</div>

<%= link_to "New allowed area", new_admin_allowed_area_path %>

app/views/admin/allowed_areas/new.html.erb
<h1>New allowed area</h1>

<%= render "form", admin_allowed_area: @admin_allowed_area %>

<br>

<div>
  <%= link_to "Back to allowed areas", admin_allowed_areas_path %>
</div>

app/views/admin/allowed_areas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_allowed_area %>

<div>
  <%= link_to "Edit this allowed area", edit_admin_allowed_area_path(@admin_allowed_area) %> |
  <%= link_to "Back to allowed areas", admin_allowed_areas_path %>

  <%= button_to "Destroy this allowed area", @admin_allowed_area, method: :delete %>
</div>

app/views/admin/allowed_postcodes/_allowed_postcode.html.erb
<div id="<%= dom_id allowed_postcode %>">
  <p>
    <strong>Postcode:</strong>
    <%= allowed_postcode.postcode %>
  </p>

</div>

app/views/admin/allowed_postcodes/_form.html.erb
<%= form_with(model: admin_allowed_postcode) do |form| %>
  <% if admin_allowed_postcode.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_allowed_postcode.errors.count, "error") %> prohibited this admin_allowed_postcode from being saved:</h2>

      <ul>
        <% admin_allowed_postcode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :postcode, style: "display: block" %>
    <%= form.text_field :postcode %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/allowed_postcodes/edit.html.erb
<h1>Editing allowed postcode</h1>

<%= render "form", admin_allowed_postcode: @admin_allowed_postcode %>

<br>

<div>
  <%= link_to "Show this allowed postcode", @admin_allowed_postcode %> |
  <%= link_to "Back to allowed postcodes", admin_allowed_postcodes_path %>
</div>

app/views/admin/allowed_postcodes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Allowed postcodes</h1>

<div id="admin_allowed_postcodes">
  <% @admin_allowed_postcodes.each do |admin_allowed_postcode| %>
    <%= render admin_allowed_postcode %>
    <p>
      <%= link_to "Show this allowed postcode", admin_allowed_postcode %>
    </p>
  <% end %>
</div>

<%= link_to "New allowed postcode", new_admin_allowed_postcode_path %>

app/views/admin/allowed_postcodes/new.html.erb
<h1>New allowed postcode</h1>

<%= render "form", admin_allowed_postcode: @admin_allowed_postcode %>

<br>

<div>
  <%= link_to "Back to allowed postcodes", admin_allowed_postcodes_path %>
</div>

app/views/admin/allowed_postcodes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_allowed_postcode %>

<div>
  <%= link_to "Edit this allowed postcode", edit_admin_allowed_postcode_path(@admin_allowed_postcode) %> |
  <%= link_to "Back to allowed postcodes", admin_allowed_postcodes_path %>

  <%= button_to "Destroy this allowed postcode", @admin_allowed_postcode, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pistachio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/postcode_searches/index.html.erb
<h1>Postcode Search</h1>

<%= form_tag(postcode_searches_path, method: :post) do %>
  <%= label_tag(:postcode, 'Postcode:') %>
  <%= text_field_tag(:postcode, params[:postcode]) %>


  <%= submit_tag('Check postcode') %>
<% end %>

app/views/postcode_searches/new.html.erb
<h1>Postcode Search</h1>

<% flash.each do |type, msg| %>
  <div class="alert alert-<%=type%>">
    <%= msg %>
  </div>
<% end %>

<%= form_tag(postcode_searches_path, method: :post) do %>
  <%= label_tag(:postcode, 'Postcode:') %>
  <%= text_field_tag(:postcode, params[:postcode]) %>

  <%= submit_tag('Check postcode') %>
<% end %>